# Theme Settings
title: Ravinder Chadha
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
logo: assets/images/self.png

# Site Settings
locale: "en-US"
description: >
  Software Developer with expertise in Python, JavaScript, and Flutter. 
  Currently working as a Data Engineer at RapidFort USA.
  Passionate about building scalable solutions and contributing to open-source projects.
search: true
repository: "ravinder-chadha/ravinder-chadha.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Social Sharing
social:
  type: Person
  links:
    - "https://linkedin.com/in/ravinder-chadha"
    - "https://github.com/ravinder-chadha"

# Site Author
author:
  name: "Ravinder Chadha"
  avatar: "/assets/images/self.png"
  bio: "Software Developer | Data Engineer"
  location: "India"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ravinderchadha1233@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ravinder-chadha"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ravinder-chadha"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
