title: Ravinder Chadha
logo: assets/images/logo.png
description: >
  Software Developer with expertise in Python, JavaScript, and Flutter. 
  Currently working as a Data Engineer at RapidFort USA.
  Passionate about building scalable solutions and contributing to open-source projects.
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: # Add your Google Analytics ID here if you have one
social:
  linkedin: ravinder-chadha
  github: ravinder-chadha
  email: ravinderchadha1233@gmail.com
